project:
  type: website
  output-dir: docs

website:
  title: "BST680 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    collapse-level: 1
    style: "docked"
    logo: "uab_logo.png"
    search: true
    contents:
      - section: "Lecture HTML"
        contents: 
          - text: "01 - Introducing Your Tools"
            href: "Lectures/01_Tools/index.qmd"
            target: _blank 
          - text: "02 - Visualization Basics"
            href: "Lectures/02_VizBasics/index.qmd"
            target: _blank 
          - text: "03 - Programming Basics"
            href: "Lectures/03_Programming/index.qmd"
            target: _blank 
          - text: "04 - Data Isolation"
            href: "Lectures/04_Isolation/index.qmd"
            target: _blank 
          - text: "05 - Data Transformation"
            href: "Lectures/05_Transform/index.qmd"
            target: _blank
          - text: "06 - Advanced Visualization"
            href: "Lectures/06_Adv_Visual/index.qmd"
            target: _blank
          - text: "07 - Reshaping Data"
            href: "Lectures/07_Reshape/index.qmd"
            target: _blank
          - text: "08 - Characters and Dates"
            href: "Lectures/08_Strings/index.qmd"
            target: _blank
      - section: "Lecture PDF"
        contents:
          - text: "01 - Introducing Your Tools"
            href: "pdfs/BST680 - 2024 - 01 Introducing your Tools.pdf"
            target: _blank
          - text: "02 - Visualization Basics"
            href: "pdfs/BST680 - 2024 - 02 Basics of Data Visualization.pdf"
            target: _blank 
          - text: "03 - Programming Basics"
            href: "pdfs/BST680 - 2024 - 03 Programming Basics.pdf"
            target: _blank 
          - text: "04 - Data Isolation"
            href: "pdfs/BST680 - 2024 - 04 dplyr Basics.pdf"
            target: _blank 
          - text: "05 - Data Transformation"
            href: "pdfs/BST680 - 2024 - 05 Transforming Data.pdf"
            target: _blank
          - text: "06 - Advanced Visualization"
            href: "pdfs/BST680 - 2024 - 06 Advanced Visualization.pdf"
            target: _blank
          - text: "07 - Reshaping Data"
            href: "pdfs/BST680 - 2024 - 07 Reshaping Data.pdf"
            target: _blank
          - text: "08 - Characters and Dates"
            href: "pdfs/BST680 - 2024 - 08 Characters and Dates.pdf"
            target: _blank
      - section: "Additional Info"
        contents:
          - text: "01a - Intro to Quarto and gt()"
            href: "html_files/01_Intro/intro_to_Quarto.qmd"
      - section: "Assignments"
        contents: 
          - text: "01 - Working with Tables"
            href: "html_files/01_Intro/exercises.qmd" 
          - text: "02 - Visualization Basics"
            href: "html_files/02_Visual/exercises_start_here.qmd" 
          - text: "03 - Programming Basics"
            href: "html_files/03_Program/class_exercises.qmd" 
          - text: "04 - Isolation with dplyr"
            href: "html_files/04_Isolate/class_exercises.qmd" 
          - text: "05 - Data Transformation"
            href: "html_files/05_Transform/class_exercises.qmd"
          - text: "06 - Advanced Visualization"
            href: "html_files/06_Adv_Visual/class_exercises.qmd"
          - text: "07 - Reshaping Data"
            href: "html_files/07_Reshape/class_exercises.qmd"
          - text: "08 - Characters and Dates"
            href: "html_files/08_Strings/class_exercises.qmd"
      - section: "Assignment Solutions"
        contents: 
          - text: "01 - Working with Tables"
            href: "html_files/01_Intro/exercise_solutions.qmd" 
          - text: "02 - Visualization Basics"
            href: "html_files/02_Visual/exercise_solutions.qmd" 
          - text: "03 - Programming Basics"
            href: "html_files/03_Program/exercise_solutions.qmd" 
          - text: "04 - Isolation with dplyr"
            href: "html_files/04_Isolate/exercise_solutions.qmd" 
          - text: "05 - Data Transformation"
            href: "html_files/05_Transform/exercise_solutions.qmd"
          - text: "06 - Advanced Visualization"
            href: "html_files/06_Adv_Visual/exercise_solutions.qmd"
          - text: "07 - Reshaping Data"
            href: "html_files/07_Reshape/exercise_solutions.qmd"
        
          
            
      - section: "Downloads"
        contents: 
          - text: "Exercise Downloads"
            href: "downloads.qmd"
      
      - section: "Midterm"
        contents: 
          - text: "Midterm Details"
            href: "html_files/Midterm/midterm_start_here.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true




