---
title: "BST680 Downloads"
---

# Exercise Downloads

All exercises can be downloaded here in both .qmd and .R formats

### Rendering .qmd files

To properly render Quarto Markdown files, be sure to download the .rds solutions and data files

Solutions are in a .zip file that should be extracted in the same location as the .qmd file to properly render

## 01 - Introducing Your Tools

Exercises - <a href="_static/01_exercises.qmd" download>[.qmd file]</a>

Solutions folder - <a href="_static/01_solutions.zip" download>[.zip file]</a>

## 02 - Visualization Basics

Exercises - <a href="_static/02_exercises.qmd" download>[.qmd file]</a>

Solutions folder - <a href="_static/02_solutions.zip" download>[.zip file]</a>

## 03 - Programming Basics

Exercises - <a href="_static/03_class_exercises.qmd" download>[.qmd file]</a> and <a href="_static/03_class_exercises.R" download>[.R file]</a>

Solutions folder - <a href="_static/03_solutions.zip" download>[.zip file]</a>

## 04 - Data Isolation

Exercises - <a href="_static/04_class_exercises.qmd" download>[.qmd file]</a> and <a href="_tatic/04_class_exercises.R" download>[.R file]</a>

Data and Solutions folder - <a href="_static/04_solutions.zip" download>[.zip file]</a>

## 05 - Data Transformation

Exercises - <a href="_static/05_class_exercises.qmd" download>[.qmd file]</a> and <a href="_static/05_class_exercises.R" download>[.R file]</a>

Data and Solutions folder - <a href="_static/05_solutions.zip" download>[.zip file]</a>

## 06 - Advanced Visualization

Exercises - <a href="_static/06_class_exercises.qmd" download>[.qmd file]</a> and <a href="_static/06_class_exercises.R" download>[.R file]</a>

Data and Solutions folder - <a href="_static/06_solutions.zip" download>[.zip file]</a>

## 07 - Reshaping Data

Exercises - <a href="_static/07_class_exercises.qmd" download>[.qmd file]</a> and <a href="_static/07_class_exercises.R" download>[.R file]</a>

Data and Solutions folder - <a href="_static/07_solutions.zip" download>[.zip file]</a>

## 08 - Characters and Dates

Exercises - <a href="_static/08_class_exercises.qmd" download>[.qmd file]</a> and <a href="_static/08_class_exercises.R" download>[.R file]</a>

Data and Solutions folder - <a href="_static/08_solutions.zip" download>[.zip file]</a>

## 09 - Joins and I/O

Exercises - <a href="_static/09_class_exercises.qmd" download>[.qmd file]</a> and <a href="_static/09_class_exercises.R" download>[.R file]</a>

Data and Solutions folder - <a href="_static/09_solutions.zip" download>[.zip file]</a>

## Midterm

The midterm project can be downloaded <a href="_static/midterm.zip" download>[here as a .zip]</a>