########################## DATA VISUALIZATION TOOLS ############################

######## LOAD PACKAGES ########

library(tidyverse)  # includes dplyr - filter / select
library(gt)
library(readxl)
library(janitor)

######## LOAD DATA ########

supermarket <- read_excel(
  # the file location
  path = "data/Supermarket Transactions.xlsx",
  # the sheet name to pull data from
  # you can also use numeric order of sheets
  sheet = "Data"
)

######## DATA DICTIONARY ########

# Review this briefly and use it as a reference to engage with the exercises below.

supermarket_descr <-
  c(
    "Transaction"        = "transaction number",
    "Purchase Date"      = "date of purchase",
    "Customer ID"        = "customer identification",
    "Gender"             = "--",
    "Marital Status"     = "--",
    "Homeowner"          = "--",
    "Children"           = "number of kids at home",
    "Annual Income"      = "income of customer",
    "City"               = "--",
    "State or Province"  = "--",
    "Country"            = "Canada, Mexico, or USA",
    "Product Family"     = "drink, food, or non-consumable",
    "Product Department" = "the item's department",
    "Product Category"   = "the item's type",
    "Units Sold"         = "number of items sold",
    "Revenue"            = "money generated by the transaction"
  )

# the enframe function transforms a vector into a tibble,
enframe(supermarket_descr) |> 
  gt(rowname_col = "name") |>
  tab_stubhead(label = 'Variable name') |> 
  cols_label(value = 'Variable description') |>
  cols_align('right') |>
  tab_header(title = 'Description of Super Market data')

################################################################################
################################################################################
################################################################################

### Exercise 1

# Use the `janitor` package to clean your dataset's names. Then, 
  # group your data by city and gender,
  # compute the sum of revenue for each group

# In the summarized data, 
  # Convert gender to a factor with categories (hint: `fct_recode`)
    # 'Male customers'
    # 'Female customers'
  # Convert `city` to a factor with levels ordered by revenue (hint: `fct_reorder`)

# Don't forget to `ungroup` your data after summarizing!
  
  
  
  
  
  
  
#################################
### Exercise 2

# Using the summarized data from exercise 1, re-create the figure presented during lecture:
  
  
  
  
  
  
  
#################################
### Exercise 3

# Create two datasets: `left_label` and `right_label`:
  # `left_label` should contain the rows of your summarized data from exercise 1 
    # that are on the left hand side of the plot from exercise 2. 
  # `right_label` should contain the rows of your summarized data from exercise 1 
    #that are on the right hand side of the plot from exercise 2.







#################################
### Exercise 4

# Add two text geometries to your figure from exercise 1. Use `nudge_x` to 
  # shift your text to the right and left of the points.







#################################
### Exercise 5

# Create a dataset called `big_diff` that shows the absolute value of the 
  # difference in revenue generated between male customers and female customers in each city.
# Filter this dataset so that only cities with difference 
  # greater than $750 are retained.
# Filter the `right_label` data from exercise 3 to retain only the rows 
  # where `city` is in `big_diff$city` values.
# Create a dataset called `highlight` that filters your summarized data from 
  #exercise 1 to retain only the rows where `city` is in `dig_diff$city`







#################################
### Exercise 6

#Create a plot similar to that from exercise 4, but this time 
  # Make lines and points have `alpha` of 1/2. 
  # Color the lines `'grey'`
  # Use only the `right_label` data to add text to the plot
  # Set `label` to be the difference in revenue rather than revenue.







#################################
### Exercise 7

# Add lines and points to the figure you created in exercise 6, using the `highlight` 
  # data you created in exercise 5.

# Use `scale_x_continuous`, setting `labels` to `scales::dollar` so that your 
  # x-axis will show dollar signs.

# Modify your x-axis and y-axis labels.







#################################
### Exercise 8

# Apply color palettes, theme elements, and legend manipulations to make your 
  # figure clear and concise. 














